apiVersion: v1
kind: Service
metadata:
  name: httpd01
  namespace: sushant
  labels:
    run: httpd01
spec:
  ports:
  - port: 80
    name: httpdxp
    protocol: TCP
    targetPort: 80
  externalIPs:
    - 192.168.137.101
  selector:
    run: httpd01
