apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    name: nginxp
    protocol: TCP
    targetPort: 80
  externalIPs:
    - 192.168.137.102
  selector:
    run: my-nginx
