apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-deploy-01
          image: docker.io/mysql:10-mar-22
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: "/var/lib/mysql"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql01
                  key: password
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: nfs-pvc-02
