apiVersion: v1
kind: Service
metadata:
  name: httpd01-service
  labels:
    run: httpd01
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.137.101
  selector:
    app: httpd01
