apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-01
spec:
  capacity:
    storage: 100Mi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /mnt/vol02
    server: 192.168.137.100
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: nfs
