apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod02
spec:
  volumes:
    - name: nginx-pvc-storage
      persistentVolumeClaim:
        claimName: nfs-pvc-01
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "nginx-server"
      volumeMounts:
        - name: nginx-pvc-storage
          mountPath: "/usr/share/nginx/html"
