apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-02
spec:
  capacity:
    storage: 200Mi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /var/nfsshare/pv01
    server: 192.168.137.10
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: master-local
